title:
randomized: false
questions:

 - type: "multiple-choice"
   question: "What does Spatial Mapping encompass?"
   items:
    - choice: Creating a map of space, including planets and their moons.
      correct: null
    - choice: Creating a 3D map of the real-world environment, often through a continously updating mesh. .
      correct: True
    - choice: Creating models of 3D objects.
      correct: null

 - type: "multiple-choice"
   question: "Which are the spatial awareness most common usage scenarios?"
   items:
    - choice: Placement, occlusion, physics and navigation.
      correct: True
    - choice: Flight, navigation and storyboarding.
      correct: null
    - choice: Mapping, annotating, button creation and gaze detection.
      correct: null

 - type: "multiple-choice"
   question: "How does audio improve an immersive experience?"
   items:
    - choice: By adding the component of music to the experience.
      correct: null
    - choice: By allowing the user to interact with objects by speaking.
      correct: null
    - choice: By mimicking sounds that the user would expect to hear using auditory cues that enhance the sense of realism inside the app.
      correct: True